repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: make flake8
        language: system
        types_or: [python, flake8]
    -   id: black
        name: black
        entry: make black
        language: system
        files: (^pyproject\.toml|\.py)$
